name: Release

on:
  push:
    tags:
      - \d+.\d+.\d+

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@eb843fa04b91b8bc5d4953899e3fff15c95f347c
        with:
          formula-name: ponyc
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_RELEASE_TOKEN }}
