name: Trigger nightly builds

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  trigger-nightly-builds-on-cirrusci:
    name: Trigger nightly builds on CirrusCI
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-release:20191107
    steps:
      - uses: actions/checkout@v1
      - name: Send curl request
        run: bash .ci-scripts/trigger-nightly-builds.bash
        env:
          CIRRUS_ACCESS_TOKEN: ${{ secrets.CIRRUS_ACCESS_TOKEN }}
